baseURL = 'https://fund.suddengunter.com/'
languageCode = 'uk-UA'
title = 'Допоможи ППОП - Харків'
theme = "arabica"
author = "suddengunter"
plainify = false

[params]
    dateFormatToUse = "2006-01-02"
    replaceGoogleFonts = "fonts.loli.net"
    twitter = "suddengunter"
    custom_css = ["css/progress.css","css/spoiler.css"]